# Generated by Django 5.1.4 on 2024-12-09 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('CustomerID', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('CustomerName', models.CharField(max_length=255)),
                ('CustomerAddress', models.CharField(max_length=255)),
                ('CustomerPhone', models.CharField(max_length=15)),
                ('CustomerAge', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CustomerBill',
            fields=[
                ('BillID', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('BillDate', models.DateField()),
                ('Price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerHoliday',
            fields=[
                ('CustomerHolidayID', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('CustomerHolidayName', models.CharField(max_length=255)),
                ('CustomerHolidayBegin', models.DateField()),
                ('CustomerHolidayEnd', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='CustomerStyle',
            fields=[
                ('CustomerStyleID', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('CustomerStyleName', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Flower',
            fields=[
                ('FlowerId', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('FlowerName', models.CharField(max_length=255)),
                ('FlowerColor', models.CharField(max_length=100)),
                ('FlowerDescription', models.TextField()),
                ('Image', models.TextField()),
                ('Price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='FlowerContaining',
            fields=[
                ('FlowerContainingID', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('FlowerContainingName', models.CharField(max_length=255)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='FlowerSize',
            fields=[
                ('FlowerSizeID', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('FlowerSizeName', models.CharField(max_length=255)),
                ('NumofFlower', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FlowerType',
            fields=[
                ('FlowerTypeId', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('FlowerTypeName', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('PaymentID', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('PaymentName', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerAccount',
            fields=[
                ('AccountID', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('AccountName', models.CharField(max_length=255)),
                ('AccountPassword', models.CharField(max_length=255)),
                ('AccountType', models.CharField(max_length=255)),
                ('CustomerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.customer')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerFeedBack',
            fields=[
                ('FeedBackID', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('Content', models.TextField()),
                ('CustomerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.customer')),
                ('FlowerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.flower')),
            ],
        ),
        migrations.AddField(
            model_name='flower',
            name='FlowerTypeId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.flowertype'),
        ),
        migrations.CreateModel(
            name='OrderList',
            fields=[
                ('OrderID', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('count', models.IntegerField()),
                ('FlowerContainingID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.flowercontaining')),
                ('FlowerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.flower')),
                ('FlowerSizeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.flowersize')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BillID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.customerbill')),
                ('CustomerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.customer')),
                ('OrderID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.orderlist')),
            ],
        ),
        migrations.AddField(
            model_name='customerbill',
            name='PaymentID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.payment'),
        ),
        migrations.CreateModel(
            name='CustomerStyleFlower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CustomerStyleID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.customerstyle')),
                ('FlowerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.flower')),
            ],
            options={
                'unique_together': {('CustomerStyleID', 'FlowerID')},
            },
        ),
        migrations.CreateModel(
            name='CustomerHolidayFlower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CustomerHolidayID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.customerholiday')),
                ('FlowerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.flower')),
            ],
            options={
                'unique_together': {('CustomerHolidayID', 'FlowerID')},
            },
        ),
    ]
