# Generated by Django 5.1.4 on 2024-12-11 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_customeraccount_groups_customeraccount_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeraccount',
            name='CustomerID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.customer'),
        ),
    ]
